spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev   # 开发环境
  application:
    name: shenghuochild-config-dev
---
spring:
  profiles: test   # 测试环境
  application:
    name: shenghuochild-config-test
# 请保存为UTU-8格式